// SPDX-License-Identifier: MIT
pragma solidity 0.8.20;

import {IERC20} from "@openzeppelin/contracts/token/ERC20/IERC20.sol";
import {IERC20Metadata} from "@openzeppelin/contracts/token/ERC20/extensions/IERC20Metadata.sol";
import {SafeERC20} from "@openzeppelin/contracts/token/ERC20/utils/SafeERC20.sol";
import {ReentrancyGuard} from "@openzeppelin/contracts/utils/ReentrancyGuard.sol";
import {Math} from "@openzeppelin/contracts/utils/math/Math.sol";
import {AggregatorV3Interface} from "@chainlink/src/v0.8/shared/interfaces/AggregatorV3Interface.sol";
import {IGuardian} from "../interfaces/IGuardian.sol";
import {IEventNotifier} from "../interfaces/IEventNotifier.sol";
import {IChromaSwapRouter} from "../interfaces/ISwapRouter.sol";

/**
 * @title PortfolioVault
 * @notice ERC-4626-compatible tokenized portfolio vault deployed as a minimal proxy.
 *
 *         Because Clones cannot call constructors, this contract implements ERC-20 and
 *         ERC-4626 manually via an {initialize} function instead of inheriting from
 *         OpenZeppelin's ERC4626 abstract contract.
 *
 *         MVP fee structure (all free at launch):
 *         - Management fee: 0% (infrastructure kept, rate set to zero).
 *         - Performance fee: removed for MVP to maximise early-user UX.
 *
 *         Future fee hooks (not active):
 *         - Boost fee (15%): charged on yield generated by YieldOptimizer.
 *         - Subscription fee: tiered access for premium features.
 *
 *         totalAssets() returns portfolio USD value via Chainlink feeds so share prices
 *         reflect true portfolio value rather than denomination-asset balance.
 */
contract PortfolioVault is ReentrancyGuard {
    using SafeERC20 for IERC20;
    using Math for uint256;

    // ─── ERC-20 storage ──────────────────────────────────────────────────────

    string private _name;
    string private _symbol;

    mapping(address => uint256) private _balances;
    mapping(address => mapping(address => uint256)) private _allowances;
    uint256 private _totalSupply;

    // ─── ERC-4626 storage ────────────────────────────────────────────────────

    /// @notice Denomination token used for deposit/withdraw accounting (e.g., USDC).
    address private _asset;

    // ─── Portfolio state ─────────────────────────────────────────────────────

    struct Asset {
        address token;
        uint256 targetWeight; // basis points; sum must equal 10 000
    }

    uint8 public riskTier;
    address public vaultOwner;
    address public guardianModule;
    address public recoveryModule;
    address public eventNotifier;
    address public swapRouter;

    /// @notice Chainlink price feed per portfolio token (and optionally the denomination asset).
    mapping(address => address) public priceFeeds;

    /// @notice Target allocation of the portfolio. Actual holdings diverge until swaps are wired in.
    Asset[] public portfolio;

    // ─── Fee state ───────────────────────────────────────────────────────────

    /// @notice Management fee rate. Set to 0 for MVP; raise via governance later.
    uint256 public constant MANAGEMENT_FEE_BPS = 0;
    uint256 public constant BPS_DENOMINATOR = 10_000;
    uint256 public constant SECONDS_PER_YEAR = 365 days;

    /// @notice Decimal precision used for all USD oracle values (matches Chainlink standard).
    uint8 public constant PRICE_DECIMALS = 8;
    /// @notice Maximum age of an accepted Chainlink price round.
    uint256 public constant PRICE_STALENESS_THRESHOLD = 1 hours;

    address public feeRecipient;

    /// @notice Timestamp of the last management-fee accrual.
    uint256 public lastFeeAccrual;

    // ─── Future fee hooks (not active in MVP) ────────────────────────────────

    /// @notice Boost fee on YieldOptimizer yield. Activated when YieldOptimizer ships.
    uint256 public constant BOOST_FEE_BPS = 1_500; // 15% of optimized yield

    /// @notice Subscription status per user (reserved for premium-tier features).
    mapping(address => bool) public hasActiveSubscription;

    // ─── Init guard ──────────────────────────────────────────────────────────

    bool private _initialized;

    // ─── Events ──────────────────────────────────────────────────────────────

    // ERC-20
    event Transfer(address indexed from, address indexed to, uint256 value);
    event Approval(address indexed owner, address indexed spender, uint256 value);

    // ERC-4626
    event Deposit(address indexed caller, address indexed owner, uint256 assets, uint256 shares);
    event Withdraw(
        address indexed caller,
        address indexed receiver,
        address indexed owner,
        uint256 assets,
        uint256 shares
    );

    // Vault-specific (security events remain here; financial events route through EventNotifier)
    event OwnershipTransferred(address indexed previousOwner, address indexed newOwner);
    event GuardianAddressUpdated(address indexed newGuardian);

    // ─── Errors ──────────────────────────────────────────────────────────────

    error AlreadyInitialized();
    error Unauthorized();
    error ZeroAmount();
    error ZeroAddress();
    error InvalidWeights();
    error ExceedsMax();
    error GuardianApprovalRequired();
    error InsufficientAllowance();
    error NoPriceFeed(address token);
    error InvalidPrice(address token);
    error StalePriceFeed(address token);
    error SwapFailed();

    // ─── Modifiers ───────────────────────────────────────────────────────────

    modifier onlyOwner() {
        if (msg.sender != vaultOwner) revert Unauthorized();
        _;
    }

    // ─── Initializer ─────────────────────────────────────────────────────────

    /**
     * @notice Initialises the vault. Called once by VaultFactory immediately after cloning.
     * @param owner_           Vault owner.
     * @param tier_            Risk tier (0 = Low, 1 = Medium, 2 = High).
     * @param asset_           Denomination asset for ERC-4626 accounting.
     * @param feeRecipient_    Address that receives management fee shares and performance fees.
     * @param eventNotifier_   EventNotifier contract for centralized financial event emission.
     * @param guardianModule_  Shared guardian module address (address(0) to disable).
     * @param recoveryModule_  Social recovery module address (address(0) to disable).
     *                         Immutable after deployment — cannot be changed by the owner.
     * @param tokens_          Portfolio token addresses (must match weights_ and priceFeeds_).
     * @param weights_         Allocation weights in basis points; must sum to 10 000.
     * @param priceFeeds_      Chainlink price feed per portfolio token (address(0) = no feed).
     */
    function initialize(
        address owner_,
        uint8 tier_,
        address asset_,
        address feeRecipient_,
        address eventNotifier_,
        address guardianModule_,
        address recoveryModule_,
        address[] calldata tokens_,
        uint256[] calldata weights_,
        address[] calldata priceFeeds_
    ) external {
        if (_initialized) revert AlreadyInitialized();
        if (owner_ == address(0) || asset_ == address(0) || feeRecipient_ == address(0)) revert ZeroAddress();
        if (tokens_.length == 0 || tokens_.length != weights_.length) revert InvalidWeights();
        if (tokens_.length != priceFeeds_.length) revert InvalidWeights();
        _assertWeightsSum(weights_);

        _initialized = true;
        vaultOwner = owner_;
        riskTier = tier_;
        _asset = asset_;
        feeRecipient = feeRecipient_;
        eventNotifier = eventNotifier_;
        guardianModule = guardianModule_;
        recoveryModule = recoveryModule_;
        lastFeeAccrual = block.timestamp;

        string memory tierLabel = tier_ == 0 ? "Low" : tier_ == 1 ? "Medium" : "High";
        _name   = string.concat("Chroma ", tierLabel, " Risk Vault");
        _symbol = string.concat("CV-", tier_ == 0 ? "LOW" : tier_ == 1 ? "MED" : "HIGH");

        for (uint256 i = 0; i < tokens_.length; i++) {
            portfolio.push(Asset({token: tokens_[i], targetWeight: weights_[i]}));
            if (priceFeeds_[i] != address(0)) {
                priceFeeds[tokens_[i]] = priceFeeds_[i];
            }
        }
    }

    // ─── ERC-4626 ────────────────────────────────────────────────────────────

    /// @notice Denomination token used for all deposit/withdraw operations.
    function asset() public view returns (address) {
        return _asset;
    }

    /// @notice Returns total portfolio value in USD with {PRICE_DECIMALS} (8) decimals.
    /// @dev Used for ERC-4626 share math so shares are priced in USD, not denomination-asset units.
    function totalAssets() public view returns (uint256) {
        return _calculatePortfolioValue();
    }

    /**
     * @notice Fetches and validates the latest USD price from a Chainlink feed.
     * @param token Portfolio token whose registered feed is queried.
     * @return price USD price with {PRICE_DECIMALS} (8) decimals.
     */
    function getTokenPrice(address token) public view returns (uint256 price) {
        address feed = priceFeeds[token];
        if (feed == address(0)) revert NoPriceFeed(token);

        (
            uint80 roundId,
            int256 answer,
            ,
            uint256 updatedAt,
            uint80 answeredInRound
        ) = AggregatorV3Interface(feed).latestRoundData();

        if (answer <= 0)                                      revert InvalidPrice(token);
        if (updatedAt == 0 || answeredInRound < roundId)     revert StalePriceFeed(token);
        if (block.timestamp - updatedAt > PRICE_STALENESS_THRESHOLD) revert StalePriceFeed(token);

        price = uint256(answer);
    }

    // ─── ERC-4626 share math ─────────────────────────────────────────────────
    //
    // totalAssets() returns USD value (8 decimals). To keep share math consistent,
    // all conversions between denomination-token amounts and shares normalise via
    // _assetToUsd / _usdToAsset so the same unit (USD 8-dec) is used on both sides
    // of every mulDiv call.

    function convertToShares(uint256 assets_) public view returns (uint256) {
        return _convertToShares(_assetToUsd(assets_), Math.Rounding.Floor);
    }

    function convertToAssets(uint256 shares_) public view returns (uint256) {
        return _usdToAsset(_convertToAssets(shares_, Math.Rounding.Floor));
    }

    function maxDeposit(address) public pure returns (uint256) { return type(uint256).max; }
    function maxMint(address)   public pure returns (uint256) { return type(uint256).max; }

    function maxWithdraw(address owner_) public view returns (uint256) {
        return _usdToAsset(_convertToAssets(_balances[owner_], Math.Rounding.Floor));
    }

    function maxRedeem(address owner_) public view returns (uint256) {
        return _balances[owner_];
    }

    function previewDeposit(uint256 assets_) public view returns (uint256) {
        return _convertToShares(_assetToUsd(assets_), Math.Rounding.Floor);
    }

    function previewMint(uint256 shares_) public view returns (uint256) {
        return _usdToAsset(_convertToAssets(shares_, Math.Rounding.Ceil));
    }

    function previewWithdraw(uint256 assets_) public view returns (uint256) {
        return _convertToShares(_assetToUsd(assets_), Math.Rounding.Ceil);
    }

    function previewRedeem(uint256 shares_) public view returns (uint256) {
        return _usdToAsset(_convertToAssets(shares_, Math.Rounding.Floor));
    }

    /**
     * @notice Deposit `assets_` of the denomination token and receive vault shares.
     * @dev ERC-4626 compliant. Enforces receiver == msg.sender for self-custody safety.
     *      When a swap router is configured, assets are converted into the target portfolio
     *      allocation before shares are calculated so pricing reflects the real holdings.
     */
    function deposit(uint256 assets_, address receiver) public nonReentrant returns (uint256 shares) {
        if (assets_ == 0) revert ZeroAmount();
        if (receiver == address(0)) revert ZeroAddress();
        if (receiver != msg.sender) revert Unauthorized();
        if (assets_ > maxDeposit(receiver)) revert ExceedsMax();

        _accrueManagementFee();

        // Snapshot share count using pre-deposit totalAssets (excludes incoming tokens).
        // Uses USD value so share math stays consistent with totalAssets() units (8 dec).
        shares = _convertToShares(_assetToUsd(assets_), Math.Rounding.Floor);

        IERC20(_asset).safeTransferFrom(msg.sender, address(this), assets_);

        if (swapRouter != address(0) && portfolio.length > 0) {
            _swapToPortfolio(assets_);
        }

        _mint(receiver, shares);
        emit Deposit(msg.sender, receiver, assets_, shares);
        if (eventNotifier != address(0)) {
            IEventNotifier(eventNotifier).emitDeposit(msg.sender, address(this), riskTier, assets_, shares, totalAssets());
        }
    }

    /**
     * @notice Mint exactly `shares_` vault tokens, pulling the required asset amount from caller.
     * @dev TODO: After receiving denomination asset, swap into target portfolio allocation.
     */
    function mint(uint256 shares_, address receiver) public nonReentrant returns (uint256 assets_) {
        if (shares_ == 0) revert ZeroAmount();
        if (receiver == address(0)) revert ZeroAddress();

        _accrueManagementFee();

        assets_ = previewMint(shares_);
        _executeDeposit(msg.sender, receiver, assets_, shares_);

        // TODO: Call SwapRouter to convert `assets_` into portfolio allocation.
    }

    /**
     * @notice Withdraw `assets_` of denomination token. Backward-compatible overload (no guardian signature).
     * @dev Calls the full withdraw with block.timestamp deadline and empty signature.
     *      Succeeds without a signature when no guardian is configured for the vault.
     */
    function withdraw(
        uint256 assets_,
        address receiver,
        address owner_
    ) external nonReentrant returns (uint256 shares) {
        return _withdrawImpl(assets_, receiver, owner_, block.timestamp, new bytes(0));
    }

    /**
     * @notice Withdraw `assets_` of the denomination token by burning the required shares.
     * @dev ERC-4626 compliant. Enforces receiver == owner == msg.sender for self-custody safety.
     *      Guardian approval required when {guardianModule} is set.
     *      No fees charged in MVP; users receive 100% of proceeds.
     * @param deadline   Expiry timestamp for the guardian signature.
     * @param signature  EIP-712 guardian signature approving this withdrawal.
     */
    function withdraw(
        uint256 assets_,
        address receiver,
        address owner_,
        uint256 deadline,
        bytes calldata signature
    ) public nonReentrant returns (uint256 shares) {
        return _withdrawImpl(assets_, receiver, owner_, deadline, signature);
    }

    function _withdrawImpl(
        uint256 assets_,
        address receiver,
        address owner_,
        uint256 deadline,
        bytes memory signature
    ) internal returns (uint256 shares) {
        if (assets_ == 0) revert ZeroAmount();
        if (receiver == address(0)) revert ZeroAddress();
        if (receiver != msg.sender) revert Unauthorized();
        if (owner_ != msg.sender) revert Unauthorized();
        if (assets_ > maxWithdraw(owner_)) revert ExceedsMax();

        _accrueManagementFee();

        if (guardianModule != address(0)) {
            bool approved = IGuardian(guardianModule).validateWithdrawal(
                address(this), owner_, assets_, receiver, deadline, signature
            );
            if (!approved) revert GuardianApprovalRequired();
        }

        shares = previewWithdraw(assets_);

        uint256 proceeds = assets_;
        if (swapRouter != address(0) && portfolio.length > 0) {
            proceeds = _swapFromPortfolio(shares);
        }

        _executeWithdraw(msg.sender, receiver, owner_, proceeds, shares);
    }

    /**
     * @notice Redeem `shares_` vault tokens for denomination asset. Backward-compatible overload.
     */
    function redeem(
        uint256 shares_,
        address receiver,
        address owner_
    ) external nonReentrant returns (uint256 assets_) {
        return _redeemImpl(shares_, receiver, owner_, block.timestamp, new bytes(0));
    }

    /**
     * @notice Redeem `shares_` vault tokens for denomination asset.
     * @dev No fees charged in MVP; users receive 100% of proceeds.
     * @param deadline   Expiry timestamp for the guardian signature.
     * @param signature  EIP-712 guardian signature approving this withdrawal.
     */
    function redeem(
        uint256 shares_,
        address receiver,
        address owner_,
        uint256 deadline,
        bytes calldata signature
    ) public nonReentrant returns (uint256 assets_) {
        return _redeemImpl(shares_, receiver, owner_, deadline, signature);
    }

    function _redeemImpl(
        uint256 shares_,
        address receiver,
        address owner_,
        uint256 deadline,
        bytes memory signature
    ) internal returns (uint256 assets_) {
        if (shares_ == 0) revert ZeroAmount();
        if (receiver == address(0)) revert ZeroAddress();
        if (shares_ > maxRedeem(owner_)) revert ExceedsMax();

        _accrueManagementFee();

        assets_ = previewRedeem(shares_);

        if (guardianModule != address(0)) {
            bool approved = IGuardian(guardianModule).validateWithdrawal(
                address(this), owner_, assets_, receiver, deadline, signature
            );
            if (!approved) revert GuardianApprovalRequired();
        }

        if (swapRouter != address(0) && portfolio.length > 0) {
            assets_ = _swapFromPortfolio(shares_);
        }

        _executeWithdraw(msg.sender, receiver, owner_, assets_, shares_);
    }

    /**
     * @notice Exit vault entirely. Backward-compatible overload (no guardian signature).
     */
    function withdrawAll() external nonReentrant returns (uint256 assets_) {
        return _withdrawAllImpl(block.timestamp, new bytes(0));
    }

    /**
     * @notice Convenience function to exit the vault entirely, burning all caller shares.
     * @dev Applies the same guardian gate as a normal withdrawal. No fees in MVP.
     * @param deadline   Expiry timestamp for the guardian signature.
     * @param signature  EIP-712 guardian signature approving this withdrawal.
     */
    function withdrawAll(
        uint256 deadline,
        bytes calldata signature
    ) external nonReentrant returns (uint256 assets_) {
        return _withdrawAllImpl(deadline, signature);
    }

    function _withdrawAllImpl(uint256 deadline, bytes memory signature) internal returns (uint256 assets_) {
        uint256 shares = _balances[msg.sender];
        if (shares == 0) revert ZeroAmount();

        _accrueManagementFee();

        assets_ = previewRedeem(shares);

        if (guardianModule != address(0)) {
            bool approved = IGuardian(guardianModule).validateWithdrawal(
                address(this), msg.sender, assets_, msg.sender, deadline, signature
            );
            if (!approved) revert GuardianApprovalRequired();
        }

        if (swapRouter != address(0) && portfolio.length > 0) {
            assets_ = _swapFromPortfolio(shares);
        }

        _executeWithdraw(msg.sender, msg.sender, msg.sender, assets_, shares);
    }

    // ─── Fee logic ───────────────────────────────────────────────────────────

    /**
     * @notice Accrues the management fee by minting dilutive shares to {feeRecipient}.
     * @dev Rate is currently 0% (MANAGEMENT_FEE_BPS = 0) so this is a no-op in MVP.
     *      Public so keepers can still call it; also invoked before every state-changing op.
     */
    function accrueManagementFee() external {
        _accrueManagementFee();
    }

    function _accrueManagementFee() internal {
        uint256 elapsed = block.timestamp - lastFeeAccrual;
        if (elapsed == 0 || _totalSupply == 0) return;

        uint256 feeShares = (_totalSupply * MANAGEMENT_FEE_BPS * elapsed)
            / (BPS_DENOMINATOR * SECONDS_PER_YEAR);

        lastFeeAccrual = block.timestamp;

        if (feeShares > 0) {
            _mint(feeRecipient, feeShares);
            if (eventNotifier != address(0)) {
                IEventNotifier(eventNotifier).emitManagementFee(address(this), riskTier, feeShares, totalAssets());
            }
        }
    }

    // ─── Module setters ──────────────────────────────────────────────────────

    /// @notice Sets the swap router used to convert tokens on deposit and withdrawal.
    function setSwapRouter(address swapRouter_) external onlyOwner {
        swapRouter = swapRouter_;
    }

    /**
     * @notice Transfers vault ownership to a new address.
     * @dev Callable by the current owner or by the registered {recoveryModule}.
     */
    function transferOwnership(address newOwner) external {
        if (msg.sender != vaultOwner && msg.sender != recoveryModule) revert Unauthorized();
        if (newOwner == address(0)) revert ZeroAddress();
        emit OwnershipTransferred(vaultOwner, newOwner);
        vaultOwner = newOwner;
    }

    /**
     * @notice Updates the guardian address registered in the guardian module.
     * @dev Callable by the vault owner directly or by the registered {recoveryModule}.
     *      Allows social recovery to rotate a compromised guardian without owner wallet access.
     */
    function setGuardianAddress(address newGuardian) external {
        if (msg.sender != vaultOwner && msg.sender != recoveryModule) revert Unauthorized();
        IGuardian(guardianModule).setGuardian(address(this), newGuardian, "");
        emit GuardianAddressUpdated(newGuardian);
    }

    /// @notice Returns the current vault owner (IVault-compatible alias for {vaultOwner}).
    function owner() external view returns (address) {
        return vaultOwner;
    }

    // ─── ERC-20 implementation ───────────────────────────────────────────────

    function name()        public view returns (string memory) { return _name; }
    function symbol()      public view returns (string memory) { return _symbol; }
    function decimals()    public pure returns (uint8)         { return 18; }
    function totalSupply() public view returns (uint256)       { return _totalSupply; }

    function balanceOf(address account) public view returns (uint256) {
        return _balances[account];
    }

    function allowance(address owner_, address spender) public view returns (uint256) {
        return _allowances[owner_][spender];
    }

    function approve(address spender, uint256 amount) public returns (bool) {
        _approve(msg.sender, spender, amount);
        return true;
    }

    function transfer(address to, uint256 amount) public returns (bool) {
        _transfer(msg.sender, to, amount);
        return true;
    }

    function transferFrom(address from, address to, uint256 amount) public returns (bool) {
        _spendAllowance(from, msg.sender, amount);
        _transfer(from, to, amount);
        return true;
    }

    // ─── Internal helpers ────────────────────────────────────────────────────

    // Virtual offsets (+1) prevent inflation attacks and division-by-zero at initialisation.
    // Both functions operate in USD (8 dec) so they stay consistent with totalAssets().
    function _convertToShares(uint256 usdAmount, Math.Rounding rounding) internal view returns (uint256) {
        return usdAmount.mulDiv(_totalSupply + 1, totalAssets() + 1, rounding);
    }

    function _convertToAssets(uint256 shares_, Math.Rounding rounding) internal view returns (uint256) {
        return shares_.mulDiv(totalAssets() + 1, _totalSupply + 1, rounding);
    }

    /// @dev Converts denomination-token amount to USD (8 dec), matching totalAssets() units.
    function _assetToUsd(uint256 assetAmount) internal view returns (uint256) {
        uint8 dec = IERC20Metadata(_asset).decimals();
        address feed = priceFeeds[_asset];
        if (feed != address(0)) {
            return (assetAmount * getTokenPrice(_asset)) / (10 ** dec);
        }
        return _scaleDecimals(assetAmount, dec, PRICE_DECIMALS);
    }

    /// @dev Converts USD (8 dec) back to denomination-token amount.
    function _usdToAsset(uint256 usdAmount) internal view returns (uint256) {
        uint8 dec = IERC20Metadata(_asset).decimals();
        address feed = priceFeeds[_asset];
        if (feed != address(0)) {
            return (usdAmount * (10 ** dec)) / getTokenPrice(_asset);
        }
        return _scaleDecimals(usdAmount, PRICE_DECIMALS, dec);
    }

    function _executeDeposit(address caller, address receiver, uint256 assets_, uint256 shares) internal {
        IERC20(_asset).safeTransferFrom(caller, address(this), assets_);
        _mint(receiver, shares);
        emit Deposit(caller, receiver, assets_, shares);
        if (eventNotifier != address(0)) {
            IEventNotifier(eventNotifier).emitDeposit(caller, address(this), riskTier, assets_, shares, totalAssets());
        }
    }

    function _executeWithdraw(
        address caller,
        address receiver,
        address owner_,
        uint256 assets_,
        uint256 shares
    ) internal {
        if (caller != owner_) {
            _spendAllowance(owner_, caller, shares);
        }
        _burn(owner_, shares);
        IERC20(_asset).safeTransfer(receiver, assets_);
        emit Withdraw(caller, receiver, owner_, assets_, shares);
        if (eventNotifier != address(0)) {
            IEventNotifier(eventNotifier).emitWithdrawal(caller, address(this), riskTier, assets_, shares, totalAssets());
        }
    }

    function _mint(address to, uint256 amount) internal {
        _totalSupply += amount;
        _balances[to] += amount;
        emit Transfer(address(0), to, amount);
    }

    function _burn(address from, uint256 amount) internal {
        _balances[from] -= amount;
        _totalSupply -= amount;
        emit Transfer(from, address(0), amount);
    }

    function _transfer(address from, address to, uint256 amount) internal {
        _balances[from] -= amount;
        _balances[to] += amount;
        emit Transfer(from, to, amount);
    }

    function _approve(address owner_, address spender, uint256 amount) internal {
        _allowances[owner_][spender] = amount;
        emit Approval(owner_, spender, amount);
    }

    function _spendAllowance(address owner_, address spender, uint256 amount) internal {
        uint256 current = _allowances[owner_][spender];
        if (current == type(uint256).max) return;
        if (current < amount) revert InsufficientAllowance();
        _allowances[owner_][spender] = current - amount;
    }

    function _calculatePortfolioValue() internal view returns (uint256 totalValue) {
        for (uint256 i = 0; i < portfolio.length; i++) {
            address token = portfolio[i].token;
            if (token.code.length == 0) continue;
            uint256 balance = IERC20(token).balanceOf(address(this));
            if (balance == 0) continue;

            address feed = priceFeeds[token];
            if (feed == address(0)) continue;

            uint256 price = getTokenPrice(token);
            uint8 tokenDec = IERC20Metadata(token).decimals();
            totalValue += (balance * price) / (10 ** tokenDec);
        }

        uint256 denomBalance = IERC20(_asset).balanceOf(address(this));
        if (denomBalance > 0) {
            uint8 denomDec = IERC20Metadata(_asset).decimals();
            address denomFeed = priceFeeds[_asset];
            if (denomFeed != address(0)) {
                totalValue += (denomBalance * getTokenPrice(_asset)) / (10 ** denomDec);
            } else {
                totalValue += _scaleDecimals(denomBalance, denomDec, PRICE_DECIMALS);
            }
        }
    }

    function _scaleDecimals(uint256 amount, uint8 fromDec, uint8 toDec) internal pure returns (uint256) {
        if (toDec >= fromDec) return amount * (10 ** (toDec - fromDec));
        return amount / (10 ** (fromDec - toDec));
    }

    function _assertWeightsSum(uint256[] calldata weights_) internal pure {
        uint256 sum;
        for (uint256 i = 0; i < weights_.length; i++) sum += weights_[i];
        if (sum != BPS_DENOMINATOR) revert InvalidWeights();
    }

    /// @dev Splits `depositAmount` of the denomination asset across the portfolio per target weights
    ///      and calls SwapRouter.swapToPortfolio(). The vault must hold depositAmount before calling.
    function _swapToPortfolio(uint256 depositAmount) internal {
        uint256 n = portfolio.length;
        address[] memory tokensOut = new address[](n);
        uint256[] memory amountsIn = new uint256[](n);

        uint256 remaining = depositAmount;
        for (uint256 i = 0; i < n; i++) {
            tokensOut[i] = portfolio[i].token;
            if (i == n - 1) {
                amountsIn[i] = remaining;
            } else {
                uint256 slice = (depositAmount * portfolio[i].targetWeight) / BPS_DENOMINATOR;
                amountsIn[i] = slice;
                remaining   -= slice;
            }
        }

        IERC20(_asset).forceApprove(swapRouter, depositAmount);
        IChromaSwapRouter(swapRouter).swapToPortfolio(_asset, tokensOut, amountsIn);
    }

    /// @dev Swaps the proportional share of each portfolio token back to the denomination asset.
    ///      `sharesToRedeem` must not exceed _totalSupply. Returns total denomination asset received.
    function _swapFromPortfolio(uint256 sharesToRedeem) internal returns (uint256 proceeds) {
        uint256 supply = _totalSupply;
        uint256 n      = portfolio.length;
        address[] memory tokensIn  = new address[](n);
        uint256[] memory amountsIn = new uint256[](n);

        for (uint256 i = 0; i < n; i++) {
            address token   = portfolio[i].token;
            uint256 balance = IERC20(token).balanceOf(address(this));
            uint256 amount  = balance * sharesToRedeem / supply;
            tokensIn[i]  = token;
            amountsIn[i] = amount;
            if (amount > 0) {
                IERC20(token).forceApprove(swapRouter, amount);
            }
        }

        proceeds = IChromaSwapRouter(swapRouter).swapToInputToken(tokensIn, amountsIn, _asset);
    }
}
